<a href="https://colab.research.google.com/github/Siddhant254/NLP/blob/master/Feature_Extraction_in_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
# Creating our data
data = {'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],
        'output':[1,1,0,0]}

df = pd.DataFrame(data)
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [5]:
# Importing vectorizer package from sklearn
from sklearn.feature_extraction.text import CountVectorizer

# Creating vectorizer object
cv = CountVectorizer()

In [6]:
# Transforming our text column
bow = cv.fit_transform(df['text'])

In [7]:
# Vocabulary -> Gives index position of the words in our table
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [8]:
# Converting each sentence into vectors
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


# N-GRAM

In [9]:
data = {'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],
        'output':[1,1,0,0]}

df = pd.DataFrame(data)
# Creating vectorizer object
n_gram = CountVectorizer(ngram_range=(2,2))  # Creating bi-gram object

bow = n_gram.fit_transform(df['text'])

# Vocabulary -> Gives index position of the words in our table
print(n_gram.vocabulary_)

# Converting each sentence into vectors
print(bow[0].toarray())
print(bow[1].toarray())

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}
[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


# TF-IDF

In [11]:
# Import TF-IDF package
from sklearn.feature_extraction.text import TfidfVectorizer

# Creating object
tfidf = TfidfVectorizer()

# Fitting and transforming data and making array
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [13]:
# IDF Values
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
